### ISSUE TITLE
Contingency Planner

### ISSUE THREAD

**Issue by mlpinit** [ImperfectSoftware/pandemic#51]
# Tasks

## GET request

POST `/games/:game_id/special_cards`

- [x] returns error if current player is not the contingency planner
- [x] returns error if current player is not the active player
- [x] returns a list of all the non duplicate discarded special cards. (if it's duplicate, it was used twice and it cannot be reused)

## POST request

POST `/games/:game_id/special_cards`
payload: `special_card_staticid`

- [x] returns error if current player is not the contingency planner
- [x] returns error if current player is not the active player
- [x] returns error if no actions left
- [x] returns error if another player has more than 7 cards
- [x] returns error if the special card is not part of the discarded special cards
- [x] increases game actions taken by 1
- [x] place special card in the player's inventory
